# ADDDATE ADICIONA UM INTERVALO DE DATA. SELECT ADDDATE("2017-06-15", INTERVAL 10 DAY);

# FUNÇÃO ADDTIME SOMA SEGUNDOS A DATA E HORA QUE TENHO 
# FUNÇÃO CURDATE ME TRAZ A DATA DO PC NO MOMENTO
# FUNÇÃO CURRENT_TIME ME TRAZ SOMENTE A HORA
# FUNÇÃO CURRENT_DATE ME TRAZ SOMENTE O ANO
# FUNÇÃO datediff PEGA DUAS DATAS E VE AS DIFERENÇAS EM DIAS( DATA FINAL, DATA INICIAL)
# FUNÇÃO DATE_ADD SOMA DIAS A DATA QUE TENHO
# FUNÇÃO DAYNAME ME DA O NOME DO DIA DA SEMANA DA DATA


SELECT CURDATE();
SELECT current_time();
SELECT CURRENT_timestamp();
SELECT YEAR( current_timestamp());
SELECT DAY (current_timestamp());
SELECT MONTH( current_timestamp());
SELECT MONTHNAME(CURRENT_TIMESTAMP());

SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2019-01-01') AS RESULTADO;
SELECT DATEDIFF(CURRENT_TIMESTAMP(), '1993-08-04') AS RESULTADO;

SELECT DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;

SELECT DISTINCT DATA_VENDA FROM notas_fiscais;

SELECT DISTINCT DATA_VENDA, 
DAYNAME(DATA_VENDA) AS DIA,
 MONTHNAME(DATA_VENDA) AS MES,
 YEAR(DATA_VENDA) AS ANO
 FROM notas_fiscais;
 
 SELECT * FROM tabela_de_clientes;
 
SELECT NOME, TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS    IDADE
FROM  tabela_de_clientes