SELECT * FROM itens_notas_fiscais;
#vendas validas e vendas invalidas
SELECT * FROM notas_fiscais;

#JUNTANDO PLANILHAS
SELECT * FROM notas_fiscais NF INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO;

#AGRUPANDO VENDAS POR DATA
SELECT NF.CPF, NF.DATA_VENDA, INF.QUANTIDADE FROM notas_fiscais NF
 INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO;
 
#AJUSTANDO AS DATAS, RETIRANDO DIA
SELECT NF.CPF, date_format(NF.DATA_VENDA,'%Y-%m') AS MES_ANO, INF.QUANTIDADE FROM notas_fiscais NF
 INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO;
 
/*AGRUPANDO E SOMANDO VALORES */
SELECT NF.CPF , DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO
, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS FROM NOTAS_FISCAIS NF
 INNER JOIN ITENS_NOTAS_FISCAIS INF
 ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');

/*LIMITE DE COMPRA POR CLIENTE */
SELECT * FROM TABELA_DE_CLIENTES TC;
SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE
FROM TABELA_DE_CLIENTES TC;


SELECT NF.CPF ,TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO
, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS ,
TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
 INNER JOIN ITENS_NOTAS_FISCAIS INF
 ON NF.NUMERO = INF.NUMERO
 INNER JOIN TABELA_DE_CLIENTES TC
 ON TC.CPF = NF.CPF
GROUP BY NF.CPF,TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');

SELECT NF.CPF ,TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO
, (INF.QUANTIDADE) AS QUANTIDADE_VENDAS ,
TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
 INNER JOIN ITENS_NOTAS_FISCAIS INF
 ON NF.NUMERO = INF.NUMERO
 INNER JOIN TABELA_DE_CLIENTES TC
 ON TC.CPF = NF.CPF
;

SELECT NF.CPF ,TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO
, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS , 
MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
 INNER JOIN ITENS_NOTAS_FISCAIS INF
 ON NF.NUMERO = INF.NUMERO
 INNER JOIN TABELA_DE_CLIENTES TC
 ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');



SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS, X.QUANTIDADE_LIMITE,
X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS AS DIFERENCA
FROM (
SELECT NF.CPF ,TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO
, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS , 
MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
 INNER JOIN ITENS_NOTAS_FISCAIS INF
 ON NF.NUMERO = INF.NUMERO
 INNER JOIN TABELA_DE_CLIENTES TC
 ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X;

SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS, X.QUANTIDADE_LIMITE,
X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS AS DIFERENCA, 
CASE WHEN (QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0 THEN 'INVÁLIDA'
ELSE 'VÁLIDA' END AS STATUS_VENDA
FROM (
SELECT NF.CPF ,TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO
, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS , 
MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
 INNER JOIN ITENS_NOTAS_FISCAIS INF
 ON NF.NUMERO = INF.NUMERO
 INNER JOIN TABELA_DE_CLIENTES TC
 ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X;


SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS, X.QUANTIDADE_LIMITE,
CASE WHEN (QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0 THEN 'INVÁLIDA'
ELSE 'VÁLIDA' END AS STATUS_VENDA
FROM (
SELECT NF.CPF ,TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO
, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS , 
MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
 INNER JOIN ITENS_NOTAS_FISCAIS INF
 ON NF.NUMERO = INF.NUMERO
 INNER JOIN TABELA_DE_CLIENTES TC
 ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X;